name: Publish to @exizent NPM org
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registery-url: "https://registry.npmjs.org"
      - name: Install dependencies and build
        run: npm install && npm run build
      - name: Publish on NPM
        run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.EXIZENT_NPM_TOKEN }}